language: java
jdk:
 - oraclejdk8
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS sysc; update user set authentication_string=PASSWORD('password') where User='user'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;'
  - sudo mysql_upgrade
  - sudo service mysql restart
deploy:
  provider: heroku
  app:
    add-tests: fourth-year-pms
  api_key:
    secure: Bm5srbAyLsBdjYQ9d0Xj8S4HeQrBoJmTkOMJMGQxSDo+GFYIdiQTtGKTHcQBQoXzmvMIoPIWZi9eaQSQ6duJmkqGitVC6PkOEv87KCbefmmOkC2FkRcQoyE2UQTdM6dw59mPROsVPxpGbti+B94f/zT3+KRdeWDMtqjrtGfwHeV1N0A1sUIKJrE75bOWVYNjWU7/QbYULE1ALdA3Dd8Bjec5wqHeLhnI1VfSvg78jSJrEchcn9uTxP7zg9g3STtKik0nX2qXamZD3auDz/ETF2JNX4esHJ84S/Mc7huu2KieM/oTSqNwbBK2gc1Ywqn+2HESTTezaAXFHdO7D+41yNF7iUQZgV18onMQpN/eTp/d97wBVxEkYWxgnfA/V+ZBam046JNDNSYouqzf9bkc3dLNhr5QV34jQn1ulM7rsL1UsjT5uVrD4rzalzMaQhOwOY0ALGUoSXoXyxhliDA2MTyWazJ7qAqpFWhK73OAYhgspadFlydUYQjXZa2ehjVx6Pe07fJKjqGz61DqC+HG1cnlUKMnmFtEto+1qaL6NJBdgI4WPTdafkCl8ZsW9JiuXt1nJdJc31uNvTmqwlss+EVohw9GeTFRGTRtl+dy9N62uCmctnQ1ACKyzo8pyboaAj+KjTcL4dil13a6B6/bZxgc5n40E/MhbpJQT3MYeuY=
